[project]
name = "intel-pcn"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
	"certifi",
	"charset-normalizer",
	"curl-cffi>=0.13.0",
	"idna",
	"requests",
	"urllib3",
]
